name: jax-fenics-adjoint
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-mp=3.1.0
  - aspy.yaml=1.3.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cached-property=1.5.1
  - certifi=2019.11.28
  - cfgv=3.0.0
  - cmake=3.16.4
  - cycler=0.10.0
  - cyipopt=0.1.9
  - dbus=1.13.6
  - decorator=4.4.2
  - editdistance=0.5.3
  - eigen=3.3.7
  - entrypoints=0.3
  - expat=2.2.9
  - fastcache=1.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - fontconfig=2.13.1
  - freetype=2.10.0
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=6.2.0
  - gmpy2=2.1.0b1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - hdf5=1.10.5
  - hypre=2.18.2
  - icu=64.2
  - identify=1.4.11
  - importlib_metadata=1.5.0
  - ipopt=3.12.13
  - ipykernel=5.1.4
  - ipyparallel=6.2.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jpeg=9c
  - jupyter_client=6.0.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - metis=5.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - mpmath=1.1.0
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - mumps-seq=5.2.1
  - ncurses=6.1
  - nodeenv=1.3.5
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - openssl=1.1.1d
  - parmetis=4.0.3
  - parso=0.6.1
  - pcre=8.44
  - petsc=3.12.4
  - petsc4py=3.12.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pkg-config=0.29.2
  - pkgconfig=1.3.1
  - prompt_toolkit=3.0.3
  - pthread-stubs=0.4
  - ptscotch=6.0.8
  - ptyprocess=0.6.0
  - pybind11=2.4.3
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - python=3.8.2
  - python-dateutil=2.8.1
  - pyyaml=5.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - readline=8.0
  - rhash=1.3.6
  - scalapack=2.0.2
  - scipy=1.4.1
  - scotch=6.0.8
  - setuptools=45.2.0
  - six=1.14.0
  - slepc=3.12.2
  - slepc4py=3.12.0
  - sqlite=3.30.1
  - suitesparse=5.6.0
  - superlu=5.2.1
  - superlu_dist=6.2.0
  - sympy=1.5.1
  - tbb=2020.1
  - tk=8.6.10
  - toml=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - virtualenv=16.7.5
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=3.0.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - appdirs==1.4.3
    - attrs==19.3.0
    - black==19.10b0
    - chardet==3.0.4
    - click==7.0
    - coverage==5.0.3
    - coveralls==1.11.1
    - docopt==0.6.2
    - dolfin-adjoint==2019.1.0
    - fdm==0.2.0
    - fenics==2019.1.0
    - flake8==3.7.9
    - idna==2.9
    - jax==0.1.59
    - jaxlib==0.1.39
    - mccabe==0.6.1
    - more-itertools==8.2.0
    - opt-einsum==3.2.0
    - packaging==20.1
    - pathspec==0.7.0
    - pluggy==0.13.1
    - pre-commit==2.1.1
    - py==1.8.1
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytest==5.3.5
    - pytest-check==0.3.7
    - pytest-cov==2.8.1
    - regex==2020.2.20
    - requests==2.23.0
    - typed-ast==1.4.1
    - urllib3==1.25.8
